### ISSUE TITLE
Hi again, I used your PKGBUILD/package again!

### ISSUE THREAD

**Issue by AM2petterk** [Sudokamikaze/linux-sk#1]
Now running Reiser4 on Linux-sk-16!

**Comment by Sudokamikaze** [comment]
Hi, thanks for notification
I'll add it back. Also, I thought It was going to be mainlined but it wasn't added

**Comment by AM2petterk** [comment]
Its a great patchset for interactive use while maintaining the power usage low on a laptop.

Currently running this with a custom config on a Dell Precision 5520 Xeon E3. Works flawless!

**Comment by Sudokamikaze** [comment]
@petter3k 
That's great, happy to hear that :3
